"""alter users table add name and email

Revision ID: 12a2c726bf0c
Revises: cabd0faa8da2
Create Date: 2020-12-23 17:39:01.936448

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12a2c726bf0c'
down_revision = 'cabd0faa8da2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('revoked_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jti', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('users', sa.Column('email', sa.String(length=70), nullable=True))
    op.add_column('users', sa.Column('name', sa.String(length=40), nullable=True))
    op.create_unique_constraint(None, 'users', ['name'])
    op.create_unique_constraint(None, 'users', ['email'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'name')
    op.drop_column('users', 'email')
    op.drop_table('revoked_tokens')
    # ### end Alembic commands ###
