"""add content and user columns to post_response

Revision ID: 23509e80e45a
Revises: 7db4e7338aeb
Create Date: 2021-01-14 17:00:15.802778

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23509e80e45a'
down_revision = '7db4e7338aeb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post_response', sa.Column('content', sa.Text(), nullable=True))
    op.add_column('post_response', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'post_response', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'post_response', type_='foreignkey')
    op.drop_column('post_response', 'user_id')
    op.drop_column('post_response', 'content')
    # ### end Alembic commands ###
