"""add article_cooperators table"

Revision ID: 2a63385d5d91
Revises: 9d62130f1dcc
Create Date: 2021-01-06 00:37:54.454779

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a63385d5d91'
down_revision = '9d62130f1dcc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('article_cooperators',
    sa.Column('article_cooperator_id', sa.Integer(), nullable=False),
    sa.Column('article_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('article_category_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['article_category_id'], ['article_categories.category_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['article_id'], ['user_article.article_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('article_cooperator_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('article_cooperators')
    # ### end Alembic commands ###
