"""add posts tables

Revision ID: 7db4e7338aeb
Revises: 904c7673a9b6
Create Date: 2021-01-14 12:08:19.154645

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7db4e7338aeb'
down_revision = '904c7673a9b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post_groups',
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('group_name', sa.String(length=255), nullable=False),
    sa.Column('creation_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('group_id'),
    sa.UniqueConstraint('group_name')
    )
    op.create_table('user_post',
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('creation_time', sa.DateTime(), nullable=True),
    sa.Column('last_modified', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('post_id')
    )
    op.create_table('post_attachments',
    sa.Column('attachment_id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.Column('file_name', sa.String(length=255), nullable=True),
    sa.Column('creation_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['user_post.post_id'], ),
    sa.PrimaryKeyConstraint('attachment_id')
    )
    op.create_table('post_cooperators',
    sa.Column('post_cooperator_id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('post_group_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['post_group_id'], ['post_groups.group_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['post_id'], ['user_post.post_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('post_cooperator_id')
    )
    op.create_table('post_response',
    sa.Column('response_id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.Column('creation_time', sa.DateTime(), nullable=True),
    sa.Column('last_modified', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['user_post.post_id'], ),
    sa.PrimaryKeyConstraint('response_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('post_response')
    op.drop_table('post_cooperators')
    op.drop_table('post_attachments')
    op.drop_table('user_post')
    op.drop_table('post_groups')
    # ### end Alembic commands ###
