"""Add date col to users, create user_actions table

Revision ID: 80429c1d96c9
Revises: e5e0f14bca95
Create Date: 2021-01-31 17:49:23.081786

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80429c1d96c9'
down_revision = 'e5e0f14bca95'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_actions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action_name', sa.String(length=250), nullable=True),
    sa.Column('changed_on', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('users', sa.Column('created', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'created')
    op.drop_table('user_actions')
    # ### end Alembic commands ###
