"""add last name and first name columns to users' table

Revision ID: b1fb0bedb04c
Revises: 14f89e9f8c9b
Create Date: 2021-02-10 16:56:24.356107

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b1fb0bedb04c'
down_revision = '14f89e9f8c9b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('first_name', sa.String(length=40), nullable=True))
    op.add_column('users', sa.Column('last_name', sa.String(length=60), nullable=True))
    op.drop_constraint('users_name_key', 'users', type_='unique')
    op.drop_column('users', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('name', sa.VARCHAR(length=40), autoincrement=False, nullable=True))
    op.create_unique_constraint('users_name_key', 'users', ['name'])
    op.drop_column('users', 'last_name')
    op.drop_column('users', 'first_name')
    # ### end Alembic commands ###
