"""add relation to user-article tables and is_verified column

Revision ID: d819c5e3cf82
Revises: e36ab3d51042
Create Date: 2021-01-06 01:22:27.681310

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd819c5e3cf82'
down_revision = 'e36ab3d51042'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_verified', sa.Integer(), server_default='1', nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_verified')
    # ### end Alembic commands ###
