"""add actions table

Revision ID: e7527d731459
Revises: 80429c1d96c9
Create Date: 2021-01-31 19:02:53.676063

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e7527d731459'
down_revision = '80429c1d96c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('actions', sa.Column('action_name', sa.String(length=250), nullable=True))
    op.drop_column('actions', 'name')
    op.add_column('user_actions', sa.Column('action_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'user_actions', 'actions', ['action_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_actions', type_='foreignkey')
    op.drop_column('user_actions', 'action_id')
    op.add_column('actions', sa.Column('name', sa.VARCHAR(length=250), autoincrement=False, nullable=False))
    op.drop_column('actions', 'action_name')
    # ### end Alembic commands ###
